#!/usr/bin/env bash
#### TTYD Install Module
####
#### Written by GAB3D
#### Copyright 2024 - till today
####
#### This File is distributed under GPLv3
####

#### All Credits to th33xitus for his great tool
#### https://github.com/gab-3d/Gab3d-Klipper-Utilities.git

# shellcheck enable=requires-variable-braces

# Error handling
set -Ee

# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

echo_green "****************************************"
echo_green "* Installing GABUTIL ...               *"
echo_green "****************************************"

# ## Step 1: Force apt update
apt-get update --allow-releaseinfo-change

## Step 2: Make sure all needed packages are installed

check_install_pkgs ${GABUTIL_DEPS}


if [[ ! -d "${GABUTIL_CONFIG_DIR}" ]]; then
    sudo -u "${BASE_USER}" mkdir -p "${GABUTIL_CONFIG_DIR}"
fi
if [[ ! -d "${GABUTIL_CONFIG_DIR}/shaper" ]]; then
    sudo -u "${BASE_USER}" mkdir -p "${GABUTIL_CONFIG_DIR}/shaper"
fi
if [[ ! -d "${GABUTIL_CONFIG_DIR}/backup" ]]; then
    sudo -u "${BASE_USER}" mkdir -p "${GABUTIL_CONFIG_DIR}/backup"
fi
## Step 3: Move to Home Dir as WorkingDirectoy
pushd "/home/${BASE_USER}" &> /dev/null || exit 1

## Step 4: clone KIAUH repo
echo_green "Clone GABUTIL repository ..."
gitclone GABUTIL_REPO "/home/${BASE_USER}/Gab3d-Klipper-Utilities"
popd &> /dev/null || exit 1

#add a multiline text to the end of "/home/${BASE_USER}"/printer_data/config/moonraker.conf
sudo -u "${BASE_USER}" echo -e "$GABUTIL_TEMPLATE" >> "${GABUTIL_CONFIG_DIR}/moonraker.conf";

sudo -u "${BASE_USER}" echo -e "$GABUTIL_INCLUDE" >> "${GABUTIL_CONFIG_DIR}/lib.cfg";

ln -s "/home/${BASE_USER}/Gab3d-Klipper-Utilities/gab-3d-utilities.cfg" "/home/${BASE_USER}/printer_data/config/gab-3d-utilities.cfg"
## Finish

echo_green "****************************************"
echo_green "* GABUTIL DONE                         *"
echo_green "****************************************"

