#!/usr/bin/env bash
# <Script Name>
# <Description what this module does>
# Written by <Author>
# GPL V3
########


# Source error handling, leave this in place
set -x
set -e
echo_green "****************************************"
echo_green "* Installing DASHBOARD ...             *"
echo_green "****************************************"

source /common.sh
install_cleanup_trap
check_install_pkgs ${DASHBOARD_DEPS}

unpack /filesystem/home/pi /home/"${BASE_USER}" "${BASE_USER}"
unpack /filesystem/home/root /root root
unpack /filesystem/boot /boot
apt install nginx -y
#check if /etc/nginx/sites-enabled/default exists, if so remove it
[ -f /etc/nginx/sites-enabled/default ] && rm /etc/nginx/sites-enabled/default

echo "This is an example module, install and set up what you need here!"
echo_green "$MK3SK_OS_VAR"


sudo -u "${BASE_USER}" echo -e "$DASHBOARD_TEMPLATE" >> "${DASHBOARD_CONFIG_DIR}/moonraker.conf";

# make /home/${BASE_USER}/finish.sh executable
#chmod +x /home/"${BASE_USER}"/klippain.sh

gitclone DASHBOARD_REPO "/home/${BASE_USER}/GAB-OS-HP"

ln -s /home/"${BASE_USER}/GAB-OS-HP/menu/menu.sh" /home/"${BASE_USER}/menu"

ln -s /etc/nginx/sites-available/dashboard /etc/nginx/sites-enabled/
# Unpack root at the end, so files are modified before
unpack /filesystem/root /

