#!/usr/bin/env bash
# Shebang for better file detection
# shellcheck enable=require-variable-braces

get_version() {
    local ver
    ver="$(realpath "$( dirname -- "${BASH_SOURCE[0]}")"/../src/version)"

    if [ -f "${ver}" ]; then
        cat "${ver}"
        return
    fi

    ver="$(realpath "$( dirname -- "${BASH_SOURCE[0]}")"/version)"
    cat "${ver}"
}

get_img_name() {
    local -a types
    types=(zip 7z xz)
    if [ -n "${DIST_PATH}" ]; then
        for i in "${types[@]}"; do
            find "${DIST_PATH}/image/" -type f -name "*.${i}" -printf "%p\n"
        done
    fi

    if [ -z "${DIST_PATH}" ]; then
        echo ""
    fi
}

DIST_VERSION="$(get_version)"
BASE_ZIP_IMG="$(get_img_name)"
DIST_NAME="MainsailOS"

# export Variables
export DIST_NAME
export DIST_VERSION
export BASE_ZIP_IMG

### JSON sniplet Setup
### NOTE: Please see all config files for setup variables!!!
# shellcheck disable=SC2034
JSON_PRETTY_NAME="Mainsail OS"
# shellcheck disable=SC2034
JSON_DESCRIPTION="A OS image with Klipper/Moonraker/Mainsail preinstalled for your 3D printers"
# shellcheck disable=SC2034
JSON_ICON_URL="https://os.mainsail.xyz/rpi-imager.png"
# shellcheck disable=SC2034
JSON_INIT_FORMAT="none"
# shellcheck disable=SC2034
JSON_SUPPORTED_SBC=""
# JSON_SUPPORTED_SBC="pi1-32bit pi2-32bit pi3-32bit pi3-64bit pi4-32bit pi4-64bit pi5-64bit"
#!/usr/bin/env bash
# Shebang for better file detection

# Declare Variables before exporting.
# See https://www.shellcheck.net/wiki/SC2155

BASE_IMAGE_ENLARGEROOT=4500
BASE_IMAGE_RESIZEROOT=600
# Compress not needed due compression done in workflow
BASE_RELEASE_COMPRESS=no
# Modules are valid for 32bit and 64bit images
MODULES="base,pkgupgrade,udev_fix,mainsailos(net,piconfig,klipper,is_req_preinstall,moonraker,timelapse,mainsail,crowsnest,sonar,password-for-sudo),postrename"

# export Variables
export BASE_IMAGE_ENLARGEROOT
export BASE_IMAGE_RESIZEROOT
export BASE_RELEASE_COMPRESS
export MODULES

### JSON sniplet Setup
### NOTE: Please see all config files for setup variables!!!
# shellcheck disable=SC2034
JSON_DESCRIPTION="A port of Raspberry Pi OS with preinstalled Klipper/Moonraker/Mainsail for 3D printers"
# shellcheck disable=SC2034
JSON_INIT_FORMAT="systemd"
# shellcheck disable=SC2034
JSON_PRETTY_SBC_NAME="Raspberry Pi"
#!/usr/bin/env bash
# Shebang for better file detection

# Declare Variables before exporting.
# See https://www.shellcheck.net/wiki/SC2155

BASE_ARCH="arm64"

# Keep for Bookworm template
# DOWNLOAD_URL_CHECKSUM="https://downloads.raspberrypi.org/raspios_lite_arm64_latest.sha256"
# DOWNLOAD_URL_IMAGE="https://downloads.raspberrypi.org/raspios_lite_arm64_latest.torrent"

# New locations after Bullseye turned into 'oldstable'
DOWNLOAD_URL_CHECKSUM="https://downloads.raspberrypi.com/raspios_oldstable_lite_arm64/images/raspios_oldstable_lite_arm64-2023-10-10/2023-05-03-raspios-bullseye-arm64-lite.img.xz.sha256"
DOWNLOAD_URL_IMAGE="https://downloads.raspberrypi.com/raspios_oldstable_lite_arm64/images/raspios_oldstable_lite_arm64-2023-10-10/2023-05-03-raspios-bullseye-arm64-lite.img.xz.torrent"


# export variables
export BASE_ARCH
export DOWNLOAD_URL_CHECKSUM
export DOWNLOAD_URL_IMAGE

### JSON sniplet Setup
### NOTE: Please see all config files for setup variables!!!
# shellcheck disable=SC2034
JSON_SUPPORTED_SBC="pi3-64bit pi4-64bit"
#!/usr/bin/env bash
# Shebang for better file detection
# shellcheck enable=require-variable-braces

get_version() {
    local ver
    ver="$(realpath "$( dirname -- "${BASH_SOURCE[0]}")"/../src/version)"

    if [ -f "${ver}" ]; then
        cat "${ver}"
        return
    fi

    ver="$(realpath "$( dirname -- "${BASH_SOURCE[0]}")"/version)"
    cat "${ver}"
}

get_img_name() {
    local -a types
    types=(zip 7z xz)
    if [ -n "${DIST_PATH}" ]; then
        for i in "${types[@]}"; do
            find "${DIST_PATH}/image/" -type f -name "*.${i}" -printf "%p\n"
        done
    fi

    if [ -z "${DIST_PATH}" ]; then
        echo ""
    fi
}

DIST_VERSION="$(get_version)"
BASE_ZIP_IMG="$(get_img_name)"
DIST_NAME="MainsailOS"

# export Variables
export DIST_NAME
export DIST_VERSION
export BASE_ZIP_IMG

### JSON sniplet Setup
### NOTE: Please see all config files for setup variables!!!
# shellcheck disable=SC2034
JSON_PRETTY_NAME="Mainsail OS"
# shellcheck disable=SC2034
JSON_DESCRIPTION="A OS image with Klipper/Moonraker/Mainsail preinstalled for your 3D printers"
# shellcheck disable=SC2034
JSON_ICON_URL="https://os.mainsail.xyz/rpi-imager.png"
# shellcheck disable=SC2034
JSON_INIT_FORMAT="none"
# shellcheck disable=SC2034
JSON_SUPPORTED_SBC=""
# JSON_SUPPORTED_SBC="pi1-32bit pi2-32bit pi3-32bit pi3-64bit pi4-32bit pi4-64bit pi5-64bit"
#!/usr/bin/env bash
# Shebang for better file detection

# Declare Variables before exporting.
# See https://www.shellcheck.net/wiki/SC2155

BASE_IMAGE_ENLARGEROOT=4500
BASE_IMAGE_RESIZEROOT=600
# Compress not needed due compression done in workflow
BASE_RELEASE_COMPRESS=no
# Modules are valid for 32bit and 64bit images
MODULES="base,pkgupgrade,udev_fix,mainsailos(net,piconfig,klipper,is_req_preinstall,moonraker,timelapse,mainsail,crowsnest,sonar,password-for-sudo),postrename"

# export Variables
export BASE_IMAGE_ENLARGEROOT
export BASE_IMAGE_RESIZEROOT
export BASE_RELEASE_COMPRESS
export MODULES

### JSON sniplet Setup
### NOTE: Please see all config files for setup variables!!!
# shellcheck disable=SC2034
JSON_DESCRIPTION="A port of Raspberry Pi OS with preinstalled Klipper/Moonraker/Mainsail for 3D printers"
# shellcheck disable=SC2034
JSON_INIT_FORMAT="systemd"
# shellcheck disable=SC2034
JSON_PRETTY_SBC_NAME="Raspberry Pi"
#!/usr/bin/env bash
# Shebang for better file detection

# Declare Variables before exporting.
# See https://www.shellcheck.net/wiki/SC2155

BASE_ARCH="arm64"

# Keep for Bookworm template
# DOWNLOAD_URL_CHECKSUM="https://downloads.raspberrypi.org/raspios_lite_arm64_latest.sha256"
# DOWNLOAD_URL_IMAGE="https://downloads.raspberrypi.org/raspios_lite_arm64_latest.torrent"

# New locations after Bullseye turned into 'oldstable'
DOWNLOAD_URL_CHECKSUM="https://downloads.raspberrypi.com/raspios_oldstable_lite_arm64/images/raspios_oldstable_lite_arm64-2023-10-10/2023-05-03-raspios-bullseye-arm64-lite.img.xz.sha256"
DOWNLOAD_URL_IMAGE="https://downloads.raspberrypi.com/raspios_oldstable_lite_arm64/images/raspios_oldstable_lite_arm64-2023-10-10/2023-05-03-raspios-bullseye-arm64-lite.img.xz.torrent"


# export variables
export BASE_ARCH
export DOWNLOAD_URL_CHECKSUM
export DOWNLOAD_URL_IMAGE

### JSON sniplet Setup
### NOTE: Please see all config files for setup variables!!!
# shellcheck disable=SC2034
JSON_SUPPORTED_SBC="pi3-64bit pi4-64bit"
#!/usr/bin/env bash
# Shebang for better file detection
# shellcheck enable=require-variable-braces

get_version() {
    local ver
    ver="$(realpath "$( dirname -- "${BASH_SOURCE[0]}")"/../src/version)"

    if [ -f "${ver}" ]; then
        cat "${ver}"
        return
    fi

    ver="$(realpath "$( dirname -- "${BASH_SOURCE[0]}")"/version)"
    cat "${ver}"
}

get_img_name() {
    local -a types
    types=(zip 7z xz)
    if [ -n "${DIST_PATH}" ]; then
        for i in "${types[@]}"; do
            find "${DIST_PATH}/image/" -type f -name "*.${i}" -printf "%p\n"
        done
    fi

    if [ -z "${DIST_PATH}" ]; then
        echo ""
    fi
}

DIST_VERSION="$(get_version)"
BASE_ZIP_IMG="$(get_img_name)"
DIST_NAME="MainsailOS"

# export Variables
export DIST_NAME
export DIST_VERSION
export BASE_ZIP_IMG

### JSON sniplet Setup
### NOTE: Please see all config files for setup variables!!!
# shellcheck disable=SC2034
JSON_PRETTY_NAME="Mainsail OS"
# shellcheck disable=SC2034
JSON_DESCRIPTION="A OS image with Klipper/Moonraker/Mainsail preinstalled for your 3D printers"
# shellcheck disable=SC2034
JSON_ICON_URL="https://os.mainsail.xyz/rpi-imager.png"
# shellcheck disable=SC2034
JSON_INIT_FORMAT="none"
# shellcheck disable=SC2034
JSON_SUPPORTED_SBC=""
# JSON_SUPPORTED_SBC="pi1-32bit pi2-32bit pi3-32bit pi3-64bit pi4-32bit pi4-64bit pi5-64bit"
#!/usr/bin/env bash
# Shebang for better file detection

# Declare Variables before exporting.
# See https://www.shellcheck.net/wiki/SC2155

BASE_IMAGE_ENLARGEROOT=4500
BASE_IMAGE_RESIZEROOT=600
# Compress not needed due compression done in workflow
BASE_RELEASE_COMPRESS=no
# Modules are valid for 32bit and 64bit images
MODULES="base,pkgupgrade,udev_fix,mainsailos(net,piconfig,klipper,is_req_preinstall,moonraker,timelapse,mainsail,crowsnest,sonar,password-for-sudo),postrename"

# export Variables
export BASE_IMAGE_ENLARGEROOT
export BASE_IMAGE_RESIZEROOT
export BASE_RELEASE_COMPRESS
export MODULES

### JSON sniplet Setup
### NOTE: Please see all config files for setup variables!!!
# shellcheck disable=SC2034
JSON_DESCRIPTION="A port of Raspberry Pi OS with preinstalled Klipper/Moonraker/Mainsail for 3D printers"
# shellcheck disable=SC2034
JSON_INIT_FORMAT="systemd"
# shellcheck disable=SC2034
JSON_PRETTY_SBC_NAME="Raspberry Pi"
#!/usr/bin/env bash
# Shebang for better file detection

# Declare Variables before exporting.
# See https://www.shellcheck.net/wiki/SC2155

BASE_ARCH="arm64"

# Keep for Bookworm template
# DOWNLOAD_URL_CHECKSUM="https://downloads.raspberrypi.org/raspios_lite_arm64_latest.sha256"
# DOWNLOAD_URL_IMAGE="https://downloads.raspberrypi.org/raspios_lite_arm64_latest.torrent"

# New locations after Bullseye turned into 'oldstable'
DOWNLOAD_URL_CHECKSUM="https://downloads.raspberrypi.com/raspios_oldstable_lite_arm64/images/raspios_oldstable_lite_arm64-2023-10-10/2023-05-03-raspios-bullseye-arm64-lite.img.xz.sha256"
DOWNLOAD_URL_IMAGE="https://downloads.raspberrypi.com/raspios_oldstable_lite_arm64/images/raspios_oldstable_lite_arm64-2023-10-10/2023-05-03-raspios-bullseye-arm64-lite.img.xz.torrent"


# export variables
export BASE_ARCH
export DOWNLOAD_URL_CHECKSUM
export DOWNLOAD_URL_IMAGE

### JSON sniplet Setup
### NOTE: Please see all config files for setup variables!!!
# shellcheck disable=SC2034
JSON_SUPPORTED_SBC="pi3-64bit pi4-64bit"
