#!/usr/bin/env bash
#### KIAUH Install Module
####
#### Written by GAB3D
#### Copyright 2022 - till today
####
#### This File is distributed under GPLv3
####

#### All Credits to th33xitus for his great tool
#### https://github.com/Frix-x/klippain

# shellcheck disable=all

# KIAUH repo
[[ -n "$KLIPPAIN_REPO_SHIP" ]] || KLIPPAIN_REPO_SHIP="https://github.com/Frix-x/klippain-shaketune.git"
[[ -n "$KLIPPAIN_REPO_BRANCH" ]] || KLIPPAIN_REPO_BRANCH="main"
[[ -n "$KLIPPAIN_VENV_DIR" ]] || KLIPPAIN_VENV_DIR="/home/${BASE_USER}/klippain_shaketune-env" 
[[ -n "$KLIPPAIN_DIR" ]] || KLIPPAIN_DIR="/home/${BASE_USER}/klippain_shaketune/" 


[[ -n "$KLIPPAIN_DEPS" ]] || KLIPPAIN_DEPS="git python3-dev python3-venv libopenblas-dev libatlas-base-dev"

KLIPPAIN_MOONRAKER='
[moonraker]'