#!/usr/bin/env bash
#### TTYD Install Module
####
#### Written by GAB3D
#### Copyright 2024 - till today
####
#### This File is distributed under GPLv3
####

#### All Credits to th33xitus for his great tool
#### https://github.com/th33xitus/kiauh

# shellcheck enable=requires-variable-braces

# Error handling
set -Ee

# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap


echo_green "****************************************"
echo_green "* Installing TTYD ...                  *"
echo_green "****************************************"

## Step 1: Force apt update
apt-get update --allow-releaseinfo-change

## Step 2: Make sure all needed packages are installed
echo_green "Installing ttyd Dependencies ..."
check_install_pkgs ${TTYD_DEPS}

## Step 3: Move to Home Dir as WorkingDirectoy
pushd "/home/${BASE_USER}" &> /dev/null || exit 1

## Step 4: clone KIAUH repo
echo_green "Clone TTYD repository ..."
gitclone TTYD_REPO ttyd
popd &> /dev/null || exit 1

## Step 5: Install TTYD
echo_green "Install TTYD ..."
pushd "/home/${BASE_USER}/ttyd" &> /dev/null || exit 1
mkdir build
cd build
cmake ..
echo_green "Building TTYD ..."
make
echo_green "Installing TTYD ..."
su -c "${BASE_USER}/ttyd/build" -c "make install"

echo_green "Installing TTYD Service ..."
su -c "cp ttyd /opt/" 
unpack /filesystem/etc/systemd/system /etc/systemd/system root
systemctl_if_exists enable ttyd

## Step 6: Cleanup
echo_green "Cleanup ..."
popd &> /dev/null || exit 1

## adding tmux to login shell
echo_green "Adding TTYD to login shell ..."


echo -e "$TTYD_LOGIN_VAR" >> "/home/${BASE_USER}/.bashrc"
## cleanup TTYD var
unset TTYD_LOGIN_VAR

## Finish
echo_green "Installing TTYD ... DONE!"

echo_green "****************************************"
echo_green "* TTYD DONE                            *"
echo_green "****************************************"


