#!/usr/bin/env bash
#### KAMP Install Module
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2022 - till today
####
#### This File is distributed under GPLv3
####

#### All Credits to th33xitus for his great tool
#### https://github.com/Frix-x/KAMP-shaketune.git

# shellcheck enable=requires-variable-braces

# Error handling
set -Ee

# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap


echo_green "Installing KAMP ..."




## Step 3: Move to Home Dir as WorkingDirectoy
pushd "/home/${BASE_USER}" &> /dev/null || exit 1

## Step 4: clone KAMP repo
echo_green "Clone KAMP repository ..."
gitclone KAMP_REPO Klipper-Adaptive-Meshing-Purging


#add a multiline text to the end of "/home/${BASE_USER}"/printer_data/config/moonraker.conf
sudo -u "${BASE_USER}" echo -e "$KAMP_TEMPLATE" >> "${KAMP_CONFIG_DIR}/moonraker.conf";

sudo -u "${BASE_USER}" echo -e "$KAMP_INCLUDE" >> "${KAMP_CONFIG_DIR}/lib.cfg";

ln -s "/home/${BASE_USER}/Klipper-Adaptive-Meshing-Purging/Configuration" "/home/${BASE_USER}/printer_data/config/KAMP"
cp "/home/${BASE_USER}/Klipper-Adaptive-Meshing-Purging/Configuration/KAMP_Settings.cfg" "/home/${BASE_USER}/printer_data/config/KAMP_Settings.cfg"



## Cleanup template
if [[ -f "${KAMP_TEMPLATE}" ]]; then
    rm -f "${KAMP_TEMPLATE}"
fi

## Finish
echo_green "Installing KAMP ... DONE!"
